services:
  clipboard-river-server:
    image: crestfallmax/clipboard-river-server:latest
    container_name: clipboard-river-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
